# Generated by Django 6.0.4 on 2026-04-12 20:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                (
                    "nivel",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=150)),
                ("dataInicio", models.DateField()),
                ("dataConclusao", models.DateField()),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("Instituicao", models.CharField(max_length=100)),
                ("duracao", models.IntegerField()),
                ("creditos", models.IntegerField()),
                ("informacao", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DescricaoDescisoes", models.CharField(max_length=250)),
                ("Erros", models.CharField(max_length=150)),
                ("Correcoes", models.CharField(max_length=150)),
                ("Justificacao", models.CharField(max_length=250)),
                ("usoAI", models.BooleanField()),
                ("FotoCaderno", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("Disciplina", models.CharField(max_length=100)),
                ("URL", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200)),
                ("ConceitosAplicados", models.CharField(max_length=250)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="")),
                ("githubRepo", models.URLField()),
                ("video", models.URLField()),
                ("dataRealizacao", models.DateField()),
                (
                    "NotaFinal",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=150)),
                ("descricao", models.CharField(max_length=200)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("URL", models.URLField()),
                (
                    "interesseNivel",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("semestre", models.CharField(max_length=20)),
                ("creditos", models.IntegerField()),
                ("descricao", models.CharField(max_length=200)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="")),
                ("URL", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200)),
                ("destaque", models.BooleanField(default=False)),
                ("URL", models.URLField()),
                (
                    "orientador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.professor",
                    ),
                ),
            ],
        ),
    ]
