# Generated by Django 6.0.4 on 2026-04-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MakingOF",
            new_name="MakingOFF",
        ),
    ]
