# Generated by Django 6.0.4 on 2026-04-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_makingof_makingoff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="licenciatura",
            old_name="informacao",
            new_name="semestre",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="Disciplina",
        ),
        migrations.AddField(
            model_name="professor",
            name="Disciplina",
            field=models.ManyToManyField(blank=True, to="portfolio.uc"),
        ),
    ]
