# Generated by Django 6.0.4 on 2026-04-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename_informacao_licenciatura_semestre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="area",
            field=models.ManyToManyField(blank=True, to="portfolio.competencia"),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciatura",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.licenciatura",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologia",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
    ]
