# Generated by Django 6.0.4 on 2026-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_tfc_area_tfc_imagem_tfc_licenciatura_tfc_tecnologia"),
    ]

    operations = [
        migrations.AddField(
            model_name="uc",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uc",
            name="avaliacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="uc",
            name="codigo_legivel",
            field=models.CharField(default="SEM_CODIGO", max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uc",
            name="course_code",
            field=models.IntegerField(default=260),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uc",
            name="lingua",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="uc",
            name="obrigatorio",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="uc",
            name="programa",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="uc",
            name="URL",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="uc",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="uc",
            name="nome",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="uc",
            name="semestre",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
