# Generated by Django 6.0.5 on 2026-05-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0005_uc_ano_uc_avaliacao_uc_codigo_legivel_uc_course_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="email",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="professor",
            name="nome",
            field=models.CharField(max_length=300),
        ),
    ]
