# Generated by Django 6.0.5 on 2026-05-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_professor_email_alter_professor_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="URL",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="professor",
            name="email",
            field=models.EmailField(max_length=500),
        ),
    ]
