# Generated by Django 6.0.5 on 2026-05-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_professor_url_alter_professor_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="nome",
            field=models.TextField(),
        ),
    ]
