# Generated by Django 6.0.5 on 2026-05-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_alter_professor_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formacao",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="tipo",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="titulo",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="makingoff",
            name="Correcoes",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="makingoff",
            name="DescricaoDescisoes",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="makingoff",
            name="Erros",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="makingoff",
            name="Justificacao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.TextField(),
        ),
    ]
